language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sddelaney/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sddelaney/multi-docker npm test

after_success:
  - docker build -t sddelaney/multi-client ./client
  - docker build -t sddelaney/multi-nginx ./nginx
  - docker build -t sddelaney/multi-worker ./worker
  - docker build -t sddelaney/multi-server ./server

  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Send to docker hub
  - docker push sddelaney/multi-nginx
  - docker push sddelaney/multi-client
  - docker push sddelaney/multi-server
  - docker push sddelaney/multi-worker